name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # At 12:00 AM, only on Monday (https://crontab.cronhub.io/)
    - cron: "0 0 * * 1"
jobs:
  waka-readme-stats-update:
    name: Update Readme with waka-readme-stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: "waka-readme-stats-total"
          WAKATIME_API_KEY: ${{ secrets.ApiWakaWaka }}
          GH_TOKEN: ${{ secrets.WakaWaka }}
          SHOW_SHORT_INFO: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE_PER_REPO: False
